package com.eby.orm.entity;
// Generated Aug 16, 2015 10:48:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private String nama;
     private Set bukus = new HashSet(0);
     private Set categories = new HashSet(0);

    public Category() {
    }

    public Category(Category category, String nama, Set bukus, Set categories) {
       this.category = category;
       this.nama = nama;
       this.bukus = bukus;
       this.categories = categories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Set getBukus() {
        return this.bukus;
    }
    
    public void setBukus(Set bukus) {
        this.bukus = bukus;
    }
    public Set getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set categories) {
        this.categories = categories;
    }




}


