package com.eby.orm.entity;
// Generated Aug 16, 2015 10:48:52 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Peminjaman generated by hbm2java
 */
public class Peminjaman  implements java.io.Serializable {


     private Integer id;
     private Anggota anggota;
     private Buku buku;
     private Date tglPinjam;
     private Date tglKembali;

    public Peminjaman() {
    }

	
    public Peminjaman(Anggota anggota, Buku buku) {
        this.anggota = anggota;
        this.buku = buku;
    }
    public Peminjaman(Anggota anggota, Buku buku, Date tglPinjam, Date tglKembali) {
       this.anggota = anggota;
       this.buku = buku;
       this.tglPinjam = tglPinjam;
       this.tglKembali = tglKembali;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Anggota getAnggota() {
        return this.anggota;
    }
    
    public void setAnggota(Anggota anggota) {
        this.anggota = anggota;
    }
    public Buku getBuku() {
        return this.buku;
    }
    
    public void setBuku(Buku buku) {
        this.buku = buku;
    }
    public Date getTglPinjam() {
        return this.tglPinjam;
    }
    
    public void setTglPinjam(Date tglPinjam) {
        this.tglPinjam = tglPinjam;
    }
    public Date getTglKembali() {
        return this.tglKembali;
    }
    
    public void setTglKembali(Date tglKembali) {
        this.tglKembali = tglKembali;
    }




}


