package com.eby.orm.entity;
// Generated Aug 16, 2015 10:48:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Penerbit generated by hbm2java
 */
public class Penerbit  implements java.io.Serializable {


     private Integer id;
     private String nama;
     private String alamat;
     private Set bukus = new HashSet(0);

    public Penerbit() {
    }

    public Penerbit(String nama, String alamat, Set bukus) {
       this.nama = nama;
       this.alamat = alamat;
       this.bukus = bukus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public Set getBukus() {
        return this.bukus;
    }
    
    public void setBukus(Set bukus) {
        this.bukus = bukus;
    }




}


